### ISSUE TITLE
gsl  android    how to bulid  the gsl.so  for android ?

### ISSUE THREAD

**Issue by taurushappy** [laheller/The-great-Android-native-library-collection#1]
Dear sir，
    I  the  down load page  the  gsl 2.7 aarch  and  qt for  android (stellarsolver for android ), but it not work correct, below is code,  i could not solve the problem, can help me 
 
 -- Found CFITSIO: /home/geo/Desktop/android_so/cfitsio_4.3.1_aarch64/lib/libcfitsio.so
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found GSL: /home/geo/qt_projects/test_a/android_so/gsl_2.7_aarch64/include (found version "2.7") 
-- Found WCSLIB: /home/geo/qt_projects/test_a/android_so/wcslib_8.2.2_aarch64/lib/libwcs.so, /home/geo/qt_projects/test_a/android_so/wcslib_8.2.2_aarch64/include/wcslib-8.2.2
-- Configuring done (0.0s)
-- Generating done (0.0s)
 is this right ?
when i use  in anroid  ,it  show 
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "cblas_sdsdot" referenced by "/data/app/~~QOBoxANgTsHWgCJ1rpwfJw==/org.wt.wsky-OKvmMEj09Hr7d--4Tvnbuw==/lib/arm64/libgsl.so"...

this is the bash code 
#! /bin/bash

# Check all the below lines and adjust all the paths starting with "${HOME}/" to the correct values

NDK_PATH=${HOME}/Android/sdk2/ndk/26.3.11579264
TOOLCHAIN="clang"
ANDROID_VERSION="26"

cmake -G"Unix Makefiles" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-${ANDROID_VERSION} \
    -DANDROID_TOOLCHAIN=${TOOLCHAIN} \
    -DCMAKE_ASM_FLAGS="--target=aarch64-linux-android${ANDROID_VERSION}" \
    -DCMAKE_TOOLCHAIN_FILE=${NDK_PATH}/build/cmake/android.toolchain.cmake \
    -DCMAKE_INSTALL_PREFIX=$(pwd)/../_deploy_aarch64 \
    -DCMAKE_C_FLAGS="-std=gnu17 -fPIE -fPIC" \
    -DCMAKE_CXX_FLAGS="-std=gnu++17 -fPIE -fPIC" \
    -DRUN_RESULT_2="" \
    -DQt5_DIR=${HOME}/Qt5.12.12/5.12.12/android_arm64_v8a/lib/cmake/Qt5 \
    -DQt5Gui_DIR=${HOME}/Qt5.12.12/5.12.12/android_arm64_v8a/lib/cmake/Qt5Gui \
    -DQt5Core_DIR=${HOME}/Qt5.12.12/5.12.12/android_arm64_v8a/lib/cmake/Qt5Core \
    -DQt5Widgets_DIR=${HOME}/Qt5.12.12/5.12.12/android_arm64_v8a/lib/cmake/Qt5Widgets \
    -DQt5Concurrent_DIR=${HOME}/Qt5.12.12/5.12.12/android_arm64_v8a/lib/cmake/Qt5Concurrent \
    -DQt5Network_DIR=${HOME}/Qt5.12.12/5.12.12/android_arm64_v8a/lib/cmake/Qt5Network \
    -DGSL_INCLUDE_DIR=${HOME}/repos/gsl_2.7_aarch64/include \
    -DGSL_LIBRARY=${HOME}/repos/gsl_2.7_aarch64/lib/libgsl.so \
    -DGSL_CBLAS_LIBRARY=${HOME}/repos/gsl_2.7_aarch64/lib/libgslcblas.so \
    -DWCSLIB_INCLUDE_DIR=${HOME}/repos/wcslib_8.2.2_aarch64/include/wcslib-8.2.2 \
    -DWCSLIB_LIBRARIES=${HOME}/repos/wcslib_8.2.2_aarch64/lib/libwcs.so \
    -DCFITSIO_INCLUDE_DIR=${HOME}/repos/cfitsio_4.3.1_aarch64/include \
    -DCFITSIO_LIBRARIES=${HOME}/repos/cfitsio_4.3.1_aarch64/lib/libcfitsio.so \
    -DBUILD_TESTS=1 \
    -DBUILD_DEMOS=1 \

**Comment by laheller** [comment]
@taurushappy 

So the error message
> E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "cblas_sdsdot" referenced by "/data/app/~~QOBoxANgTsHWgCJ1rpwfJw==/org.wt.wsky-OKvmMEj09Hr7d--4Tvnbuw==/lib/arm64/libgsl.so"

tells exactly, what's the problem.
You probably forgot to deploy the "libgsl-cblas.so" shared library.

**Comment by taurushappy** [comment]
thanks , i deploy the libgslcblas.so
in the android libs   there including libgslcblas.so
 I try to rebuild the  libgsl arrch64 ,the code is wrong  , i do not know how to build this libgsl.so arrch64
./configure CC=/home/geo/Android/sdk2/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang++ --host=aarch64 --target=aarch64 --prefix=/home/geo/Desktop/gsl_build,
this is my qt Android file .pro 
  ANDROID_EXTRA_LIBS = \
        /home/geo/qt_projects/wsky/alibs/libcrypto.so \
        /home/geo/qt_projects/wsky/alibs/libssl.so \
        /home/geo/qt_projects/wsky/alibs/libcurl.so \
        /home/geo/qt_projects/wsky/alibs/libwcs.so \
        /home/geo/qt_projects/wsky/alibs/libgslcblas.so \
        /home/geo/qt_projects/wsky/alibs/libgsl.so

**Comment by laheller** [comment]
You don't need to build the libgsl because I already did it. Check the name of this repo and the readme 😉

**Comment by taurushappy** [comment]
ok,  I really don't know where is wrong ?

-- Found CFITSIO: /home/geo/repos/cfitsio_4.3.1_aarch64/lib/libcfitsio.so
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found WCSLIB: /home/geo/repos/wcslib_8.2.2_aarch64/lib/libwcs.so, /home/geo/repos/wcslib_8.2.2_aarch64/include/wcslib-8.2.2
-- Configuring done (0.3s)
-- Generating done (0.1s)
is there wrong ?

https://android-ndk.narkive.com/cQULQeoW/why-does-my-so-library-compiled-with-ndk-won-t-work-with-error-cannot-locate-symbol-cblas-sdsdot

there is other people also have the same problem ,do not  know to solve the problem,

**Comment by laheller** [comment]
This is what you probably need:
> sudo apt install pkg-config

**Comment by taurushappy** [comment]
when  I try  readelf -Ws libgslcblas.so | grep UND
 show ,  I guess the  libgslcblas.so  don't have the  "cblas_sdsdot" function
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_finalize@LIBC (2)
     2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_atexit@LIBC (2)
     3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __register_atfork@LIBC (2)
     4: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND stderr@LIBC (2)
     5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fprintf@LIBC (2)
     6: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND vfprintf@LIBC (2)
     7: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND abort@LIBC (2)
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
   707: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_finalize
   708: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_atexit
   709: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __register_atfork
   853: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND stderr
   854: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fprintf
   855: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND vfprintf
   856: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND abort
the  file libgslcblas.so is right
readelf -Ws libgsl.so | grep UND
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_finalize@LIBC (2)
     2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_atexit@LIBC (2)
     3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __register_atfork@LIBC (2)
     4: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND malloc@LIBC (2)
     5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND free@LIBC (2)
     6: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND memset@LIBC (2)
     7: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fread@LIBC (2)
     8: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fwrite@LIBC (2)
     9: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND putc@LIBC (2)
    10: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fprintf@LIBC (2)
    11: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fscanf@LIBC (2)
    12: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND cblas_sdsdot
    13: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND cblas_dsdot
    14: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND cblas_sdot
    15: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND cblas_ddot

**Comment by taurushappy** [comment]
readelf -Ws libgslcblas.so | grep cblas_sdsdot
   142: 000000000000541c   300 FUNC    GLOBAL DEFAULT   12 cblas_sdsdot
   716: 000000000000541c   300 FUNC    GLOBAL DEFAULT   12 cblas_sdsdot
  readelf -Ws libgsl.so | grep cblas_sdsdot
    12: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND cblas_sdsdot
  6590: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND cblas_sdsdot

**Comment by laheller** [comment]
As I wrote above, you don't need to build gsl because it's already built by me.
Check the table in the readme of this repo, it has a line with GSL, just download it.

**Comment by taurushappy** [comment]
sir,  i used the GSL  lib  ( libgsl.so)  which  download  from  your shared link (page) gsl  aarch64.  

I  give up building  the stellarsolver for android ( qt on android) ，it  is too  hard to build . 

Finally,  thanks your (sir) help  and guidance.  Best  regards！
